# This workflow will build Python packages on every commit.

name: Build archinstall

on: [ push, pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Prepare arch
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
          pacman --noconfirm -Syyu
          pacman --noconfirm -Sy python-setuptools python-pip python-build
          pacman --noconfirm -Sy python-pyparted python-pydantic python-cryptography
      - name: Remove existing archinstall (if any)
        run: pip uninstall -y archinstall --break-system-packages || true
      - name: Build archinstall
        run: python -m build --wheel archinstoo
      - name: Install archinstall
        run: pip install archinstoo/dist/*.whl --break-system-packages --no-deps
      - name: Run archinstall
        run: |
          python -V
          archinstall --help
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: archinstall
          path: archinstoo/dist/*
