on: [ push, pull_request ]
name: ruff check linting
jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - uses: astral-sh/ruff-action@aedff8d295e5eafdfcc21db7dfdce8cab2c55e7b  # v3.6.0
              with:
                src: archinstoo
                args: check --config archinstoo/pyproject.toml
